// packages/app/src/apps/App.vue
<script setup lang="ts">
import {
	VueCounter,
	SvelteInVue,
	SvelteCounter,
	ReactInVue,
	ReactCounter,
} from "../lib"

let count = 2
</script>

<template>
	<h2>Vue:</h2>
	<ReactInVue :Component="ReactCounter" :props="{ count }" />
	<VueCounter :count="count" />
	<SvelteInVue :Component="SvelteCounter" :props="{ count }" />
</template>

// packages/app/src/apps/App.svelte
<script lang="ts">
    import { SvelteCounter, ReactCounter, VueCounter, ReactInSvelte, VueInSvelte } from "../lib"

	const count = 3
</script>

<h2>Svelte: </h2>

<ReactInSvelte Component={ReactCounter} props={{ count }}  />
<VueInSvelte Component={VueCounter} props={{ count }}  />
<SvelteCounter {count} />
