// packages/app/src/apps/App.vue
<script setup lang="ts">
import {
	VueCounter,
	SvelteInVue,
	SvelteCounter,
	ReactInVue,
	ReactCounter,
} from "../lib"

let count = 2
</script>

<template>
	<h2>Vue:</h2>
	<ReactInVue :Component="ReactCounter" :props="{ count }" />
	<VueCounter :count="count" />
	<SvelteInVue :Component="SvelteCounter" :props="{ count }" />
</template>

// packages/app/src/apps/App.tsx
import { ReactCounter, SvelteCounter, VueCounter, wrapSvelteInReact, wrapVueInReact } from "../lib"

const WrappedSvelteCounter = wrapSvelteInReact(SvelteCounter)
const WrappedVueCounter = wrapVueInReact(VueCounter)

function App() {
	const count = 1
	
  return (
    <>
		<h2>React:</h2>
		<ReactCounter count={count} />
		<WrappedVueCounter count={count} />
		<WrappedSvelteCounter count={count} />
    </>
  )
}

export default App
